version: '2'
services:

  # The Application
  myapp:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
     - mongo  
    environment:
      - "DB_HOST=172.23.0.1"
      - "DB_PORT=27019"
      - "DB_DATABASE=task"
      - "DB_USERNAME="
      - "DB_PASSWORD="
    ports:
      - 1337:1337
      
  mongo:
    command: mongod
    image: mongo:3.0.14
    volumes:
      - mongodata1:/data/db
      - mongoconfig1:/data/configdb
    ports:
        - "27019:27017"      

volumes:
  mongodata1:
  mongoconfig1:  
